version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout

      # Bundle install dependencies
      - run:
          name: Which bundler?
          command: |
            bundle -v
            gem install bundler

      - ruby/bundle-install

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
          cache-key: "yarn.lock"


  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
      - image: circleci/postgres:9.5-alpine
    environment:
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: ""
      RAILS_ENV: test
    executor: ruby/default
    steps:
      - checkout

      # Bundle install dependencies
      - run:
          name: Which bundler?
          command: |
            bundle -v
            gem install bundler

      - ruby/bundle-install

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
          cache-key: "yarn.lock"

      - run:
          name: Other dependencies
          command: |
            apt install sqlite-libs sqlite-dev



workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
