version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - bbb-app-one-{{ checksum "Gemfile.lock" }}
            - bbb-app-one-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      # Store bundle cache
      - save_cache:
          key: bbb-app-one-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  test:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
      - image: circleci/postgres:9.6.2-alpine
        environment:
          RAILS_ENV: test
          POSTGRES_USER: root
          POSTGRES_DB: bbb-app-one_test

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - bbb-app-one-{{ checksum "Gemfile.lock" }}
            - bbb-app-one-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install -y postgresql-client || true

      # Store bundle cache
      - save_cache:
          key: bbb-app-one-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:structure:load

      - run:
          name: Parallel RSpec
          command: bin/rails test

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
