version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout

      # Bundle install dependencies
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

      # Setup the database
      - run: bundle exec rake db:setup
