version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
     - setup_remote_docker:
         docker_layer_caching: true

#      # Restore Cached Dependencies
#      - type: cache-restore
#        name: Restore bundle cache
#        key: bbb-app-one-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - yarn install --check-files

      # Setup the database
      - run: bundle exec rake db:setup
